version: 2
deployment:
  tasks:
    # Set up Python virtual environment
    - /usr/bin/python3 -m venv venv
    - source venv/bin/activate && pip install -r requirements.txt

    # Install Node.js dependencies and build frontend
    - cd client && npm install
    - cd client && npm run build

    # Move built frontend to public_html directory
    - rm -rf ~/public_html/*
    - cp -r client/dist/* ~/public_html/

    # Restart the Flask server using gunicorn
    - source venv/bin/activate && pkill -f gunicorn || true
    - source venv/bin/activate && gunicorn --bind 0.0.0.0:5000 server.app:app --daemon
