deployment:
  tasks:
    # Step 1: Set the deployment path
    - export DEPLOYPATH=/home/votivela/public_html/votive
    - mkdir -p $DEPLOYPATH
    - echo "Deployment path set to $DEPLOYPATH" >> /home/votivela/deploy.log

    # Step 2: Create the deployment directory if it doesn't exist
    - mkdir -p $DEPLOYPATH/static
    - echo "Created deployment directory at $DEPLOYPATH" >> /home/votivela/deploy.log

    # Step 3: Build the React app (front-end)
    - cd /home/votivela/repositories/votive/client && npm install >> /home/votivela/deploy.log 2>&1
    - cd /home/votivela/repositories/votive/client && npm run build >> /home/votivela/deploy.log 2>&1
    - echo "React app built successfully" >> /home/votivela/deploy.log

    # Step 4: Copy the React build files to the deployment directory
    - /bin/cp -rf /home/votivela/repositories/votive/client/dist/* $DEPLOYPATH/static/
    - echo "React build files copied to $DEPLOYPATH/static/" >> /home/votivela/deploy.log

    # Step 5: Copy the Flask backend files to the deployment directory
    - /bin/cp -rf /home/votivela/repositories/votive/server/* $DEPLOYPATH/
    - echo "Flask backend files copied to $DEPLOYPATH" >> /home/votivela/deploy.log

    # Step 6: Copy the requirements.txt file to the deployment directory
    - /bin/cp -rf /home/votivela/repositories/votive/requirements.txt $DEPLOYPATH/
    - echo "requirements.txt copied to $DEPLOYPATH" >> /home/votivela/deploy.log

    # Step 7: Set up and activate the virtual environment
    - if [ ! -d "/home/votivela/virtualenv/votive/3.12" ]; then python3 -m venv /home/votivela/virtualenv/votive/3.12; fi
    - source /home/votivela/virtualenv/votive/3.12/bin/activate
    - echo "Virtual environment activated" >> /home/votivela/deploy.log

    # Step 8: Install Python dependencies
    - pip install -r $DEPLOYPATH/requirements.txt >> /home/votivela/deploy.log 2>&1
    - echo "Python dependencies installed" >> /home/votivela/deploy.log

    # Step 9: Restart the Flask app using Gunicorn
    - pkill -f gunicorn || true
    - gunicorn --chdir $DEPLOYPATH app:app --daemon
    - echo "Flask app restarted with Gunicorn" >> /home/votivela/deploy.log
