services:
  - name: votive-app
    type: web
    env: python
    buildCommand: "pip install -r server/requirements.txt && npm install --prefix client && npm run build --prefix client"
    startCommand: "python server/app.py"
    plan: free
